services:
  api:
    container_name: axum-api
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app       # Mount the local project directory to /app in the container
    depends_on:
      - database

  database:
    container_name: postgres-database
    image: postgres:17.2
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
      
  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    expose:
      - 8081
    ports: 
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgresql://postgres:postgres@postgres-database/postgres?sslmode=disable
    depends_on:
      - database