services:
  api:
    container_name: axum-api
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app       # Mount the local project directory to /app in the container